### ISSUE TITLE
Добавить класс center

### ISSUE THREAD

**Issue by VadimCpp** [reviakin/gorkogo55-landing#6]
В html теге в аттрибуте class можно указывать несколько значений.
Класс container определяет размер блока, а класс container-center определяет его положение по центру.

Необходимо для каждого атрибута class указать два значения:
class="container container-center"

**Comment by reviakin** [comment]
Раньше container-center cсодержал:
margin-left: auto;
margin-right: auto.

В новой версии эти стили отсутствуют.
