### ISSUE TITLE
Исследование времени загрузки

### ISSUE THREAD

**Issue by VadimCpp** [reviakin/gorkogo55-landing#68]
Провести исследование: почему так долго загружаются иконки.
Результаты исследования записать тут и обсудить с @VadimCpp

**Comment by Nebula223** [comment]
Судя по всему происходит  загрузка всех версий шрифтов, из-за большого количества запросов загрузка идёт долго. Думаю можно попробовать загрузить font-awesome с другого cdn, либо разместить прямо на сайте(так же можно попробовать убрать неиспользуемые иконки из набора)

![image](https://user-images.githubusercontent.com/23727217/65595287-b963f380-df94-11e9-8f2d-a00f7f51b07e.png)

**Comment by VadimCpp** [comment]
@Nebula223 Найди пожалуйста место в коде, в котором идет отсылка к шрифтам и вставь ссылку на коммит в issue

**Comment by Nebula223** [comment]
@VadimCpp  место где идёт отсылка к font-awesome
https://github.com/reviakin/gorkogo55-landing/blob/feab36801272361e57218dd5ffec23b39fc2d1ce/index.html#L14

Сам коммит

https://github.com/reviakin/gorkogo55-landing/pull/54

**Comment by VadimCpp** [comment]
Продолжение тут:

https://github.com/reviakin/gorkogo55-landing/issues/69
