### ISSUE TITLE
[Главная страница] Изменение структуры контента

### ISSUE THREAD

**Issue by MaxFlower** [reviakin/gorkogo55-landing#75]
Цель:
улучшить визуальное восприятие главной страницы

Описание:
Необходимо разместить данные на скриншоте секции контента в горизонтальном порядке использую колоночную систему Bootstrap (не зря же мы его подключили)

**Текущий вариант:**
![sections](https://user-images.githubusercontent.com/10515741/66779538-29e89b00-eed7-11e9-939c-9b8f661e8107.png)

**Comment by aerovir** [comment]
Беру задачу
