### ISSUE TITLE
[Главная страница] Вынести яндекс.метрику в отдельный оформленный футер

### ISSUE THREAD

**Issue by MaxFlower** [reviakin/gorkogo55-landing#76]
Цель:
улучшить визуальное восприятие главной страницы.

Описание:
Оформить футер как отдельный элемент **на всех страницах!!!**

**Текущий вид:**
![footer_current](https://user-images.githubusercontent.com/10515741/66780265-12aaad00-eed9-11e9-85a6-40e384803275.png)

При выполнении задания желательно использовать стандартные решения библиотеки Bootstrap, а вдохновиться можно дизайном футера от rambler.ru
У нас контента явно меньше, так что достаточно будет в левой части разместить надпись **ТЦ «Две пятерки»** , а в правой части яндекс.метрику сайта.
 
![footer](https://user-images.githubusercontent.com/10515741/66779937-3a4d4580-eed8-11e9-8fde-547cffa6697c.png)

**Comment by aerovir** [comment]
Беру задачу :)

**Comment by VadimCpp** [comment]
N/A
